# Generated by Django 3.0.9 on 2020-08-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(blank=True, max_length=10)),
                ('file_code', models.CharField(blank=True, max_length=10)),
                ('club_common_name', models.CharField(blank=True, max_length=100)),
                ('club_full_name', models.CharField(blank=True, max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
