# Generated by Django 3.0.9 on 2020-08-03 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='club_short_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='location_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('game_status', models.CharField(blank=True, max_length=1)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='game.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='game.Team')),
            ],
        ),
        migrations.CreateModel(
            name='AtBat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('ab_number', models.IntegerField()),
                ('result', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batter', to='game.Player')),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitcher', to='game.Player')),
                ('team_batting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_batting', to='game.Team')),
                ('team_pitching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_pitcher', to='game.Team')),
            ],
        ),
    ]
