# Generated by Django 3.1 on 2020-08-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200811_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='include_in_overlay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='include_in_tipping',
            field=models.BooleanField(default=True),
        ),
    ]
