# Generated by Django 3.0.9 on 2020-08-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200803_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='pitch_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
