# Generated by Django 3.0.9 on 2020-08-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200803_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='pitch_offset_seconds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='pitch',
            name='pitcher_height_y',
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name='pitch',
            name='video_rubber_x',
            field=models.IntegerField(default=427),
        ),
        migrations.AddField(
            model_name='pitch',
            name='video_rubber_y',
            field=models.IntegerField(default=430),
        ),
    ]
