# Generated by Django 3.1 on 2020-08-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200803_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
