# Generated by Django 3.1 on 2020-08-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_pitch_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
