# Generated by Django 3.1 on 2020-08-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_pitch_pitch_plate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='pitch_plate_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
