# Generated by Django 3.1 on 2020-08-04 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200804_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atbat',
            options={'ordering': ['ab_number']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='pitch',
            options={'ordering': ['data__game_total_pitches']},
        ),
        migrations.AlterField(
            model_name='atbat',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_bats', to='game.game'),
        ),
    ]
