# Generated by Django 3.1 on 2020-08-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200804_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='atbat',
            name='outcome_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
