# Generated by Django 3.1 on 2020-08-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_atbat_outcome_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atbat',
            options={'ordering': ['inning', '-top_bottom']},
        ),
        migrations.AlterField(
            model_name='pitch',
            name='at_bat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='game.atbat'),
        ),
    ]
