# Generated by Django 3.1 on 2020-09-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20200830_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='caption',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
