# Generated by Django 3.1 on 2020-09-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_pitch_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='caption_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
