# Generated by Django 3.1 on 2020-09-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_pitch_caption_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='strike_probability',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
