# Generated by Django 3.1 on 2021-03-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_pitch_strike_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='api_data',
            field=models.JSONField(null=True),
        ),
    ]
